name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allow manually triggering the workflow from the web UI.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools

    - name: Install Rustup targets
      run: rustup target add x86_64-unknown-linux-musl

    - name: Check out source code
      uses: actions/checkout@v1

    - name: Check
      run: cargo check

    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: target
